### ISSUE TITLE
Mapmaker Request: Reduce Vespene Geyser Footprint "No-Resource" Placement at Corners by 1

### ISSUE THREAD

**Issue by Joshua-Leibold** [Ahli/sc2xml#102]
Much of SC2 mapmaking depends on fine-tuning mineral line and geyser placement. While minerals and geysers are 1x2 and 3x3 respectively, both minerals and geysers have a much larger "No-Resource" placement apply footprint that prevents putting Command Structures too close to the resources. This helps keep the look and feel of bases more consistent by preventing mapmakers from constructing too-ridiculous looking mineral lines in melee (non-custom) maps and helps the player ingame visually identify where a Command Structure should be placed.

However, both minerals and geysers have some element of an overly restrictive footprint that prevents mapmakers from being versatile in tight conditions. In rare cases it can even directly affect Terran players ingame by blocking placement of an additional command center where a player would otherwise expect to be able to (ie. a third CC in the natural base of NeoHumanity).

REQUEST: Reduce Vespene Geyser Placement Apply/ Check "No-Resource" footprint squares by 1 at the corners
Help image: https://i.gyazo.com/8dad5b11727f65eadb66261b45c93d32.png

This is a standard LOTV base layout:

https://i.gyazo.com/08f9e8b985f94b9cf068f05407d07254.jpg

This is the same layout with the above suggestion:

https://i.gyazo.com/d3134e5a20ca930fee610b34005e5744.jpg

As you can see, the player still can clearly identify where a CC is permitted. However, removing these squares on the geyser footprint greatly opens up new opportunities for mapmakers to construct new mineral layouts. Players may not realize, but the overly restrictive footprints help restrict mineral lines to strict 45 and 90 degree angles which greatly limits map diversity since most maps entire layouts are dictated by the minute differences in the placement of the initial 3-4 bases and the way that geysers in particular block troop movement with their regularly large 3x3 footprint. Sometimes, it is preferable to move a geyser a tiny amount to allow units to path through without issue, but doing so would prevent the player from placing the Command Structure where the mapmaker intends which forces compromise on the intended design. This is a common problem since the distance from one side of a base layout to another is quite large, making rotation times from paths going through a base versus around the backside of it take forever, particularly on bases that are placed in a forward position (forward bases greatly inhibit nearby movement options on most maps, causing mapmakers to try and squish them down. example: Dragon Scales).

Here is a fun visual game showing the rather arbitrary nature of geysers prevented by these outside squares on the vespene geyser footprint: 
https://twitter.com/Omni_Skeptic/status/1673818456242679811?s=20

After doing testing of about ~1:25s, the following vespene harvesting rates were found for the newly un-restricted geysers:

https://i.gyazo.com/53bed694988c085ce0c681e2eadbcaa4.jpg

Standard "close-range" geyser (3 squares away exactly):
468 with 3 workers
352 with 2 workers

Standard "long-range" geyser (4 squares away diagonally):
468 with 3 workers
328 with 2 workers

Unrestricted Geyser Suggestion:
468 with 3 workers
324 with 2 workers

Existing Corner Geyser:
448 with 3 workers
300 with 2 workers

As you can see, the mineral efficiency is nearly identical, and it becomes identical when one considers that these kinds of geysers would never be used by mapmakers in main bases (the only place where 2 workers mine from gas reliably; these geysers are unnecessary in mains as Main bases always have adequate space and we prefer efficient geysers where possible).

If there are further concerns, contact OmniSkeptic for further info

**Comment by JoshLeibold99** [comment]
**XML Changes:**

<?xml version="1.0" encoding="utf-8"?>
<Catalog>
    <CFootprint id="FootprintGeyserRounded">
        <Layers index="Check">
            <Rows index="0" value="..ooooo.."/>
            <Rows index="1" value=".ooooooo."/>
            <Rows index="7" value=".ooooooo."/>
            <Rows index="8" value="..ooooo.."/>
        </Layers>
        <Layers index="Place">
            <Rows index="0" value="..ooooo.."/>
            <Rows index="1" value=".ooooooo."/>
            <Rows index="7" value=".ooooooo."/>
            <Rows index="8" value="..ooooo.."/>
        </Layers>
        <Shape>
            <Radius value="1.4143"/>
            <Offsets value="-1,-1;1,-1;-1,1;1,1"/>
            <Borders value="0,2,2;1,0,2;2,3,2;3,1,2"/>
        </Shape>
    </CFootprint>
</Catalog>

**Comment by Joshua-Leibold** [comment]
Successfully patched live with 5.0.13
