### ISSUE TITLE
Lurker’s main target unit can be damaged by Lurker’s attack even though this unit is in a transport/stasis/lifted

### ISSUE THREAD

**Issue by Ahli** [Ahli/sc2xml#14]
Bug reported by [냥파이어 on Blizzard's forums](https://us.forums.blizzard.com/en/sc2/t/possible-bugs-in-ladder-games/25950)

I could not re-create the issue, so I assume it is a very specific scenario. However, the data looks like it is possible due to the includes in the search area effect. Otherwise, the search area effect filters out hidden units

``` xml
    <CEffectDamage id="LurkerMPDamage">
        <ValidatorArray value="NotHidden"/>
    </CEffectDamage>
```

If someone can give me more info how to recreate the issue or show me a replay or video where this occurs, that would be great :)

TODO:
improve the fix with a unit filter that requires ground and excludes stasis and invlunerable

**Comment by blaqknight** [comment]
https://www.youtube.com/watch?v=LT5A2bN1Rg0
https://www.youtube.com/watch?v=FGo4MlVw-8Y

I'm 냥파이어! you can check this bug in that videos. thank you!

**Comment by Ahli** [comment]
Awesome! Thank you!

The above check should probably be expanded to exclude a few other things as well (lift, stasis).

**Comment by blaqknight** [comment]
Transport can make this bug includes bunkers and CC. I think all transport can make this bug.

Sorry for poor English! XD

**Comment by Ahli** [comment]
Your English is fine.

Yes, all transporters can cause this. But the same issue can happen when the unit is hit by stasis or lifted. The unit the Lurkers are targeting avoids these checks. The fact that it is hit in a transport means that the other checks from the splash damage are not happening as well

**Comment by blaqknight** [comment]
Awesome! I hope this bug be fixed asap! thank you!
