### ISSUE TITLE
PTR: Verification of female Ghost not having Snipe Cancel Button on command card

### ISSUE THREAD

**Issue by ingoschlegelmilch** [Ahli/sc2xml#2]
@Ahli Since you've asked for this over on TL.net I thought it might be easier to just add this here instead:

As you suspected already, during casting of Snipe the female Ghost's command card currently does not update correctly to display a cancel button like it does on the default male Ghost (tested on PTR version `5.0.11.89391`):

### Default Ghost
![SC2_x64_regular_ghost_short](https://user-images.githubusercontent.com/25961571/206877923-214f8d42-2799-4578-9d05-3b2eb166e242.gif)

### Female Ghost (Covert Operative)
![SC2_x64_female_ghost_short](https://user-images.githubusercontent.com/25961571/206877925-f34cdcea-af4f-483b-be8f-9d75a5c2393e.gif)

Feel free to incorporate this into your draft and thanks again for the effort you're putting into this!

**Comment by Ahli** [comment]
Awesome, thanks!
