### ISSUE TITLE
Shield Battery Overcharge ability

### ISSUE THREAD

**Issue by Sprite101** [Ahli/sc2xml#3]
The patch note says the restoration speed was changed to 150%. But I’ve checked that it remains at 200%. Hope you could verify that.

**Comment by Ahli** [comment]
Some fields have changed, but apparently not all.
I did not check that, yet.
Do you happen to know which effect has not been edited?
I remember that you said something like that very early after the PTR release in sc2mapster's discord

**Comment by Sprite101** [comment]
I’ve checked that they changed the “create healer” effect (the exact ID is “ShieldBatteryRechargeChanneledOvercharged”), where they altered the “recharge vital rate” from 72 to 54, where the normal battery recharge value is 36. 
However, in-game test shows the recharge speed has no difference. It all takes ~10 seconds to restore a nexus’s shield from empty to full.
Maybe the correct way is to change the Overcharge Behavior, where the multiplier should be changed from 2 to 1.5.

**Comment by Ahli** [comment]
In my test, it takes ~9 real seconds to refill a Nexus with overcharge.
Without overcharge, it restores about 320 shields within 6 seconds.

So, a rough estimation in PTR's unit tester:
33% in 6s => 5.5%/s
100% in 9s => 11.1%/s

That's 200% :D

Indeed, overcharge adds a behavior whose multiplier should be changed from 2  to 1.5.

Well, I still need to check what the hell they actually changed.

Also, I noticed that it regenerates more energy than it consumed while being overcharged as well. Not sure if that is supposed to be this way

**Comment by Ahli** [comment]
They changed an effect which is part of an unused ability.
The correct way to fix the overcharge bonus is to edit the behavior's heal rate multiplier
