### ISSUE TITLE
Voidray movement speed with active Prismatic Alignment is lower after Flux Vanes updgrade

### ISSUE THREAD

**Issue by Prometheus3375** [Ahli/sc2xml#94]
I learnt about this bug/feature in [this](https://youtu.be/43LyGoFjhlE) video, but the first time it was described back than it was introduced in [this post](https://us.forums.blizzard.com/en/sc2/t/bugoversight-with-void-ray-movement-speed/15823) in official bug report forum.

The issue:
> Values before Flux Vanes
Default: 3.85
Prismatic Alignment: 3.85 (-0.96) = 2.89

> Values after Flux Vanes
Default: 4.65
Prismatic Alignment: 4.65 (-2.03) = 2.62

**Comment by Ahli** [comment]
I looked at the values of the editor:
![image](https://github.com/Ahli/sc2xml/assets/5763784/b6fcc7f0-fa7b-44b4-b00c-df943f7e4b15)

The speed multiplier with Flux Vanes looks like it was designed to make Void Ray always have the same speed during Prismatic Alignment regardless of upgrades. The multiplier needs to be 0.6212 for that.

This is a balance issue and I know that the balance council will address this in the next balance patch.

TODO check good value for a fix that respects:
- follow Blizzard's initial design at the rework
- check if Prismatic Alignment's tooltip is fine with new value or if it is contradicting

**Comment by Ahli** [comment]
A fix will be done by balance council and released end of September

**Comment by Prometheus3375** [comment]
I think this one can be closed.
